**Series**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
data = {
     'student' :['joey','anna','koby'],
     'subject' :['maths','history','science'],
     'marks'   :['60','80','48']


 }
df = pd.DataFrame(data)
print(df)

  student  subject marks
0    joey    maths    60
1    anna  history    80
2    koby  science    48

In [ ]:
import pandas as pd


df = pd.read_csv("sample_data/california_housing_train.csv")

print(df.head(10))
print(df.tail(15))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0
5    -114.58     33.63                29.0       1387.0           236.0
6    -114.58     33.61                25.0       2907.0           680.0
7    -114.59     34.83                41.0        812.0           168.0
8    -114.59     33.61                34.0       4789.0          1175.0
9    -114.60     34.83                46.0       1497.0           309.0

   population  households  median_income  median_house_value
0      1015.0       472.0         1.4936             66900.0
1      1129.0       463.0         1.8200             80100.0
2       333.0       117.0         1.6509             85700.0
3       515.0       226.0         3.1917             73400.0
4       624.0       262.0         1.9250             65500.0
5       671.0       239.0         3.3438             74000.0
6      1841.0       633.0         2.6768             82400.0
7       375.0       158.0         1.7083             48500.0
8      3134.0      1056.0         2.1782             58400.0
9       787.0       271.0         2.1908             48100.0
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16985    -124.19     40.77                30.0       2975.0           634.0
16986    -124.19     40.73                21.0       5694.0          1056.0
16987    -124.21     41.77                17.0       3461.0           722.0
16988    -124.21     41.75                20.0       3810.0           787.0
16989    -124.21     40.75                32.0       1218.0           331.0
16990    -124.22     41.73                28.0       3003.0           699.0
16991    -124.23     41.75                11.0       3159.0           616.0
16992    -124.23     40.81                52.0       1112.0           209.0
16993    -124.23     40.54                52.0       2694.0           453.0
16994    -124.25     40.28                32.0       1430.0           419.0
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
16985      1367.0       583.0         2.4420             69000.0
16986      2907.0       972.0         3.5363             90100.0
16987      1947.0       647.0         2.5795             68400.0
16988      1993.0       721.0         2.0074             66900.0
16989       620.0       268.0         1.6528             58100.0
16990      1530.0       653.0         1.7038             78300.0
16991      1343.0       479.0         2.4805             73200.0
16992       544.0       172.0         3.3462             50800.0
16993      1152.0       435.0         3.0806            106700.0
16994       434.0       187.0         1.9417             76100.0
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

In [ ]:
import pandas as pd


df = pd.read_csv("sample_data/california_housing_train.csv")

print(df)
print(df.tail())

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

In [ ]:
import pandas as pd

# Simple dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['Delhi', 'Mumbai', 'Kolkata', 'Chennai', 'Pune'],
    'Score': [85, 92, 78, 88, 95]
}

# Create DataFrame
df = pd.DataFrame(data)
df.iloc[0:2,0:3]
df.loc[0:2,['Name','City']]

      Name     City
0    Alice    Delhi
1      Bob   Mumbai
2  Charlie  Kolkata

In [ ]:
print(df['Name'])
df[['City']]

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

      City
0    Delhi
1   Mumbai
2  Kolkata
3  Chennai
4     Pune

In [ ]:
df.Name

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

In [ ]:
df['Age'].iloc[:4]

0    24
1    27
2    22
3    32
Name: Age, dtype: int64

In [ ]:
df = pd.DataFrame(data)
df[['Name','City']]
df[['Age','City']]

   Age     City
0   24    Delhi
1   27   Mumbai
2   22  Kolkata
3   32  Chennai
4   29     Pune

In [ ]:
df.iloc[:2]

    Name  Age    City  Score
0  Alice   24   Delhi     85
1    Bob   27  Mumbai     92

In [ ]:
df.loc[df['City'] == 'Kolkata']

      Name  Age     City  Score
2  Charlie   22  Kolkata     78

In [ ]:
df.iloc[0]['City']

'Delhi'

In [ ]:
df.loc[:2,['Name','City']]

      Name     City
0    Alice    Delhi
1      Bob   Mumbai
2  Charlie  Kolkata

In [ ]:
df.loc[df['Name']=='Eva', 'Score' ]

4    95
Name: Score, dtype: int64

In [ ]:
df[(df['Age'] > 25) & (df['Score'] > 80)]

    Name  Age     City  Score
1    Bob   27   Mumbai     92
3  David   32  Chennai     88
4    Eva   29     Pune     95

In [ ]:
df[df['Name'].str.endswith('e')]

      Name  Age     City  Score
0    Alice   24    Delhi     85
2  Charlie   22  Kolkata     78

In [ ]:
df['Spouse'] = [2,3,4,5,2]
print(df)

      Name  Age     City  Score  Spouse
0    Alice   24    Delhi     85       2
1      Bob   27   Mumbai     92       3
2  Charlie   22  Kolkata     78       4
3    David   32  Chennai     88       5
4      Eva   29     Pune     95       2

In [ ]:
df.drop('Name', axis = 1)

   Age     City  Score  Spouse
0   24    Delhi     85       2
1   27   Mumbai     92       3
2   22  Kolkata     78       4
3   32  Chennai     88       5
4   29     Pune     95       2

In [ ]:
df = df.rename(columns = {'Age':'Ages alive '},index = {2:'two'})
print(df)

        Name  Ages alive      City  Score  Spouse
0      Alice           24    Delhi     85       2
1        Bob           27   Mumbai     92       3
two  Charlie           22  Kolkata     78       4
3      David           32  Chennai     88       5
4        Eva           29     Pune     95       2

In [ ]:
df['Country'] = 'India'
print(df)

        Name  Ages alive      City  Score  Spouse Country
0      Alice           24    Delhi     85       2   India
1        Bob           27   Mumbai     92       3   India
two  Charlie           22  Kolkata     78       4   India
3      David           32  Chennai     88       5   India
4        Eva           29     Pune     95       2   India

In [ ]:
df[df['Name'].str.startswith('A')]

    Name  Ages alive    City  Score  Spouse Country
0  Alice           24  Delhi     85       2   India

In [ ]:
import pandas as pd

# Recreate the DataFrame as it was before the drop operations
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Ages alive': [24, 27, 22, 32, 29], # 'Age' was renamed to 'Ages alive'
    'City': ['Delhi', 'Mumbai', 'Kolkata', 'Chennai', 'Pune'],
    'Score': [85, 92, 78, 88, 95]
}

df = pd.DataFrame(data)
df['Spouse'] = [2, 3, 4, 5, 2] # 'Spouse' column was added
df = df.rename(index={2:'two'}) # Index 2 was renamed to 'two'
df['Country'] = 'India' # 'Country' column was added

# Now, perform the drop operations
df = df.drop('Country', axis=1) # Drop the 'Country' column
df = df.drop('two', axis=0)      # Drop the row with index 'two'

print(df)

    Name  Ages alive     City  Score  Spouse
0  Alice          24    Delhi     85       2
1    Bob          27   Mumbai     92       3
3  David          32  Chennai     88       5
4    Eva          29     Pune     95       2

In [ ]:
df = df.drop('Country', axis=1)
df = df.drop('two', axis=0)
display(df)

    Name  Ages alive      City  Score  Spouse
0  Alice           24    Delhi     85       2
1    Bob           27   Mumbai     92       3
3  David           32  Chennai     88       5
4    Eva           29     Pune     95       2

In [ ]:
import pandas as pd

data = {'Name': ['A', 'B', 'C'], 'City': ['Pune', 'Mumbai', 'Chennai']}
backup = pd.DataFrame(data, index=['one', 'two', 'three'])

df = backup.copy()
df.at['two', 'City'] = 'Delhi'
print(df)

      Name     City
one      A     Pune
two      B    Delhi
three    C  Chennai